### ISSUE TITLE
tz_offset is incorrectly documented in the code and documentation

### ISSUE THREAD

**Issue by VPTechOps** [adafruit/Adafruit_CircuitPython_NTP#17]
The code describes the tz_offset code as:
        :param int tz_offset: The offset of the local timezone,
            in seconds west of UTC (negative in most of Western Europe,
            positive in the US, zero in the UK).
        """

        try:
            now = self._esp.get_time()
            now = time.localtime(now[0] + tz_offset)

Timezone offset in the US is negative. For example MST7 is -25200.

**Comment by ladyada** [comment]
OK! please submit a PR if ya can :)
