### ISSUE TITLE
The tz_offset attribute is a float, not an int.

### ISSUE THREAD

**Issue by BiffoBear** [adafruit/Adafruit_CircuitPython_NTP#29]
`tz_offset: int = 0` should be `tz_offset: float = 0.0` as India is at UTC +5.5 hours for example.

`self._tz_offset = tz_offset * 60 * 60` can be cast to `int` if required.

**Comment by joshua-beck-0908** [comment]
Yeah, having the exact same problem in Australia. There's lots of sloppy timezone code out there that assumes all time zones are aligned to whole-hour intervals. I'll see if I can put in a pull request.

**Comment by FoamyGuy** [comment]
resolved by #30
